Feature/19 main list screen
BeRich-Team/BeRich pull request #34
Opened 2023-04-13 14:28 UTC by IlyasNN

<img width="490" alt="Screenshot 2023-04-13 at 17 27 46" src="https://user-images.githubusercontent.com/50013971/231790962-a9129618-6b1d-457d-8487-8545c6874fd1.png">

2023-04-13 14:49 UTC, andrey-sikerin requested changes

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/Extensions/View+Extension.swift
> +        let roundedRect = RoundedRectangle(cornerRadius: cornerRadius)
RoundedRectangle(cornerRadius: cornerRadius).map {
  clipShape($0). overlay($0.strokeBorder(content, lineWidth: width)))
}

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/Fakes.swift
> +    static let tickersFakes: [Ticker] = [
tickers?

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreen.swift
> +                    .listRowInsets(EdgeInsets())
.zero?

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreen.swift
> +            .navigationTitle("BeRich")
может это тоже State?

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/ListScreen/TickerCellView.swift
> +    let ticker: Ticker
@State?

2023-04-13 14:49 UTC, andrey-sikerin commented on BeRich/Modifiers/NavigationBarColor.swift
> +private struct NavigationBarModifier: ViewModifier {
предложу переназвать файл NavigationBarModifier.swift тогда?

2023-04-13 15:52 UTC, IlyasNN commented on BeRich/Extensions/View+Extension.swift
> +//
Согласен! Бесполезная штука)
FIXED

2023-04-13 15:56 UTC, IlyasNN commented on BeRich/Extensions/View+Extension.swift
> +        let roundedRect = RoundedRectangle(cornerRadius: cornerRadius)
У RoundedRectangle нет метода .map

2023-04-13 16:00 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +            .navigationTitle("BeRich")
Что именно? Тайтл? А зачем? 
Вот вынести в переменную для удобства да, стоит

2023-04-13 16:02 UTC, IlyasNN commented on BeRich/ListScreen/TickerCellView.swift
> +    let ticker: Ticker
В нашем случае он не меняется динамически. Если будет необходимость, добавим

2023-04-13 16:05 UTC, IlyasNN commented on BeRich/Fakes.swift
> +    static let tickersFakes: [Ticker] = [
FIXED

2023-04-13 18:44 UTC, DanilaG commented on BeRich/Fakes.swift
> +struct Fakes {
Судя по всему да, чтобы избежать создание сущности (подробнее [тут](https://realm.github.io/SwiftLint/convenience_type.html))

2023-04-13 19:00 UTC, DanilaG commented on BeRich/Fakes.swift
> +struct Fakes {
FIXED

2023-04-13 20:07 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +            .navigationTitle("BeRich")
Ну у нас не мультиязычный проект, не вижу смысла)

2023-04-14 06:48 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +            .navigationTitle("BeRich")
Это да, оно не критично. Однако, оно ещё даёт дополнительные преимущества - все строки модуля в одном месте и нет дублирование строк внутри вьюх. Но думаю в течении 6 дней, мы не сможем прочувствовать эти плюсы. Поэтому можно внутри вьюхи просто в константы вынести. Сейчас тогда так и сделаю.

2023-04-14 13:20 UTC, andrey-sikerin approved these changes

2023-04-14 13:20 UTC, andrey-sikerin commented on BeRich/Extensions/View+Extension.swift
> +        let roundedRect = RoundedRectangle(cornerRadius: cornerRadius)
ок

2023-04-14 13:20 UTC, andrey-sikerin commented on BeRich/Modifiers/NavigationBarModifier.swift
> +        UINavigationBar.appearance().standardAppearance = coloredAppearance
мне не нравится что мы в конструкторе объекта вместо конфигурации объекта делаем какую-то левую работу. 

https://developer.apple.com/documentation/technotes/tn3106-customizing-uinavigationbar-appearance

предложу сконфигурировать на didFinishLaunchingWithOptions один раз

2023-04-14 13:58 UTC, andrey-sikerin requested changes

2023-04-14 13:58 UTC, andrey-sikerin commented on BeRich/ListScreen/Ticker.swift
> +    var priceChangeText: String {
extension на PriceChange?

2023-04-14 14:03 UTC, andrey-sikerin approved these changes

2023-04-14 14:04 UTC, DanilaG approved these changes

2023-04-14 14:08 UTC, merged