add network request
BeRich-Team/BeRich pull request #35
Opened 2023-04-13 19:50 UTC by Kinara32

Добавил запрос в сеть по всем тикерам бинанса

2023-04-14 08:24 UTC, StoneSpb commented
Андрей призывал сделать с использованием Swift Concurrency. Давай в следующем реквесте переделаем наше api на async.

2023-04-14 08:24 UTC, StoneSpb requested changes

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
Вроде же договорились сначала MOEX сделать 0_о

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/BinanceAPI.swift
> +    static let sceme = "https"
```suggestion
    static let scheme = "https"
```

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +protocol INetworkFetcher {
В iOS нейминге "I" использовать не принято, здесь можно было бы назвать `NetworkFetching`
Только у тебя более специфичная задача, чем абстрактная загрузка из сети - ты загружаешь данные о финансовых инструментах, поэтому можно было бы добавить специфики, сделать что-то типа `TradingDataNetworkFetcher`

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +    func getTickers(result: @escaping (BinanceTikers?) -> Void)
```suggestion
    func getTickers(completion: @escaping (BinanceTikers?) -> Void)
```

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +        network.request(path: "https://data.binance.com/api/v3/exchangeInfo", params: nil) { [weak self] data, response, error in
Лучше разбить на host + часть, специфичную для каждого запроса. Тогда тебе не придётся дублировать `https://data.binance.com` во множестве мест.

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/BinanceAPI.swift
> +    static let sceme = "https"
Почему-то эта схема не используется в реальном запросе

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +                result(nil)
У тебя код пойдёт исполняться дальше и существует вероятность, что кложура позовётся дважды.
Если ты вместо if начнёшь использовать в guard в подобных местах, тебе компилятор не даст забыть поставить return

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +                print(response.statusCode)
Довольно бессмысленное сообщение в логе. Здесь нужно либо убрать, либо добавить какой-то поясняющий текст

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +            let binanceTickers = self?.decodeJSON(type: BinanceTikers.self, from: data)
Что, если `data == nil`?

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +            let binanceTickers = self?.decodeJSON(type: BinanceTikers.self, from: data)
Я к тому, что звать какую-то логику на пустых данных по большому счёту нет смысла, красивее проверить здесь и в метод передавать уже без опциональности

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkFetcher.swift
> +        guard let data, let response = try? decoder.decode(type, from: data) else { return nil }
Вот здесь не помешал бы лог с ошибкой, что мы не смогли десериализовать данные

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkManager.swift
> +    func request(path: String, params: [String: String]?, completion: @escaping (Data?, URLResponse?, Error?) -> Void)
В сетевых запросах используется `URL` (тип), не path

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/NetworkManager.swift
> +    func request(path: String, params: [String: String]?, completion: @escaping (Data?, URLResponse?, Error?) -> Void)
Такие нетипизированные параметры бессмысленны, ты наплодишь 100500 ошибок, если будешь работать с ними в коде. Пока они не используются - давай уберём. Когда будут использоваться - сделаем enum для возможных ключей.

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/BinanceTikers.swift
> +struct Symbols: Decodable {
```suggestion
struct Symbol: Decodable {
```
?

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/BinanceTikers.swift
> +enum Status: String, Decodable {
Здесь бы чуть конкретизировать, что за статус. Например `TradingStatus`, `TradingSessionStatus`, etc

2023-04-14 08:24 UTC, StoneSpb commented on BeRich/Network/BinanceTikers.swift
Сюда бы ещё инфу о самих свечах..

2023-04-14 12:12 UTC, andrey-sikerin requested changes

2023-04-14 12:12 UTC, andrey-sikerin commented on BeRich/Network/NetworkFetcher.swift
> +                print(error)
предложу ошибку наверх кидать? - throws

2023-04-14 12:12 UTC, andrey-sikerin commented on BeRich/Network/NetworkFetcher.swift
> +        guard let data, let response = try? decoder.decode(type, from: data) else { return nil }
предложу ошибку кидать наверх а не замалчивать

2023-04-14 12:12 UTC, andrey-sikerin commented on BeRich/Network/NetworkFetcher.swift
> +    private func decodeJSON<T: Decodable>(type: T.Type, from data: Data?) -> T? {
тебе из класса ничего не нужно предложу просто иметь приватную функцию в конце файла

2023-04-14 12:12 UTC, andrey-sikerin commented on BeRich/Network/NetworkManager.swift
> +    func request(path: String, params: [String: String]?, completion: @escaping (Data?, URLResponse?, Error?) -> Void)
async/awat?

2023-04-14 12:12 UTC, andrey-sikerin commented on BeRich/Network/NetworkManager.swift
> +protocol INetworkManager {
протокол из одного метода - это фактически блок

2023-04-14 14:30 UTC, Kinara32 commented on BeRich/Network/BinanceTikers.swift
> +struct BinanceTikers: Decodable {
Да, там все по другому

2023-04-14 19:42 UTC, StoneSpb commented
Здесь бОльшая часть замечаний - coding style. Главное добавить недостающие вызовы completion, и я бы убрал фетч на onAppear. А остальное если что можно влить отдельным реквестом.

2023-04-14 19:43 UTC, StoneSpb requested changes

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
private?

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +                print(binanceTikers!)
Предлагаю убрать force unwrap

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +            }.onAppear { tradingDataNetworkFetcher.getTickers(completion: { binanceTikers in
Предлагаю не вливать этот дифф, т.к. он откровенно отладочный.

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/BinanceTikers.swift
> +            case symbol, tradingSessionStatus = "status"
Рекомендую каждый case размещать на отдельной строке, так проще ориентироваться и добавлять новые (будет меньше диффа)

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/NetworkService.swift
> +    static func request(_ path: URL, _ completion: @escaping (Result<Data, NetworkError>) -> Void) {
```suggestion
    static func request(_ url: URL, _ completion: @escaping (Result<Data, NetworkError>) -> Void) {
```

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/NetworkService.swift
> +                    completion(.failure(.badResponse))
Давай выведем error в консоль, если есть. Мне казалось так делалось в прошлой версии кода, вроде было логично

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/NetworkService.swift
> +                guard error == nil, let data = data else {
В свежей версии swift можно даже вот так подсократить:
```suggestion
                guard error == nil, let data else {
```

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/TradingDataNetworkFetcher.swift
> +protocol NetworkFetching {
```suggestion
protocol TradingDataNetworkFetching {
```

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +            ) }
Обычно такая комбинация скобок у меня вызывает чувство, что нужно переформатировать код

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/TradingDataNetworkFetcher.swift
> +                    print(error)
completion не позвали (кстати в swift concurrency у тебя бы не получилось так сделать)

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/TradingDataNetworkFetcher.swift
> +                print(error)
completion не позвали

2023-04-14 19:43 UTC, StoneSpb commented on BeRich/Network/TradingDataNetworkFetcher.swift
> +            case exchangeInfo = "https://data.binance.com/api/v3/exchangeInfo"
Я всё ещё склоняюсь к тому, что не имеет смысла для каждого урла дублировать `"https://data.binance.com/`, но предлагаю отложить до лучших времён, если что потом порефакторим

2023-04-15 11:54 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +            }.onAppear { tradingDataNetworkFetcher.getTickers(completion: { binanceTikers in
nit: можно не писать `completion: `
```
onAppear {
  tradingDataNetworkFetcher.getTickers { 
    print($0!)
  }
}
```

2023-04-15 12:06 UTC, StoneSpb approved these changes

2023-04-15 12:06 UTC, StoneSpb commented on BeRich/Network/BinanceApi.swift
> +    static let sceme = "https"
```suggestion
    static let scheme = "https"
```

2023-04-15 12:40 UTC, andrey-sikerin requested changes

2023-04-15 12:40 UTC, andrey-sikerin commented on BeRich/Network/BinanceApi.swift
> +            components.scheme = BinanceApi.scheme
кажется можно писать Self.scheme

2023-04-15 12:40 UTC, andrey-sikerin commented on BeRich/Network/BinanceApi.swift
> +            components.host = BinanceApi.host
Self.host

2023-04-15 12:40 UTC, andrey-sikerin commented on BeRich/Network/NetworkService.swift
> +                    print("Network request failed: \(error?.localizedDescription ?? "")")
мне не очень нравится что print попадут в production код - 
https://medium.com/macoclock/swift-print-only-in-debug-mode-c571d6173dfa

предложу сделать функцию котра для RELEASE не будет принтить

2023-04-15 12:40 UTC, andrey-sikerin commented on BeRich/Network/NetworkService.swift
> +                    completion(.failure(.badResponse))
предложу к твоей ошибке зацепить нижележащую underlying error например как здесь 

https://github.com/justeat/iOS.ErrorUtilities/blob/master/ErrorUtilities/NSError%2BChaining.swift -

2023-04-15 14:06 UTC, andrey-sikerin approved these changes

2023-04-15 14:06 UTC, andrey-sikerin commented on BeRich/Network/Utilities.swift
> +func printInDebugMode(_ items: Any...) {
print?

2023-04-15 14:06 UTC, andrey-sikerin commented on BeRich/Network/Utilities.swift
> +        print(items)
Swift.print?

2023-04-15 14:07 UTC, andrey-sikerin approved these changes

2023-04-15 14:07 UTC, andrey-sikerin commented on BeRich/Network/Utilities.swift
> +
предложу положить Utilities в корень (не в Network)

2023-04-15 14:19 UTC, merged