Add MVVM for first screen
BeRich-Team/BeRich pull request #40
Opened 2023-04-14 14:27 UTC by DanilaG

Добавлена:
- лоудер
- ассемблай
- viewModel

2023-04-14 14:42 UTC, andrey-sikerin requested changes

2023-04-14 14:42 UTC, andrey-sikerin commented on BeRich/ListScreen/Views/ListScreen.swift
> +    private let navigationTitle = "BeRich"
предложу просто перенести приватной глобальной переменной внизу файла

2023-04-14 14:42 UTC, andrey-sikerin commented on BeRich/ListScreen/ViewModel/ListScreenViewModel.swift
> +import Foundation
предложу пофичево проект гранить и перенести на оборот.в ListScreen что касается этого

как вот здесь


<img width="236" alt="Screen Shot 2023-04-14 at 17 37 40" src="https://user-images.githubusercontent.com/7223599/232075619-2e2e5317-0055-4692-8e0c-5494febf57de.png">

2023-04-14 14:42 UTC, andrey-sikerin commented on BeRich/RootAssembly.swift
> +final class RootAssembly: ObservableObject {
нужно чекнуться что архитектура с DI контейнерами подойдет для SwiftUI navigation controller навигации - https://sarunw.com/posts/navigation-in-swiftui/

2023-04-14 18:26 UTC, DanilaG commented on BeRich/ListScreen/Views/ListScreen.swift
> +    private let navigationTitle = "BeRich"
Поправил

2023-04-14 18:31 UTC, DanilaG commented on BeRich/RootAssembly.swift
> +final class RootAssembly: ObservableObject {
Возникли проблемы. Погуглив, не смог найти хорошего решения. [Это](https://habr.com/ru/companies/kts/articles/713848/) выглядит как рабочее, но кажется оверхед. Есть вариант стандартного локатора - EnvironmentObject, но с ним тоже есть определённые проблемы (рантайм ошибки + проблемы локатора). Решил сделать проще - добавить фабричный метод.

2023-04-14 19:25 UTC, StoneSpb commented on BeRich/RootAssembly.swift
> +final class RootAssembly: ObservableObject {
Давайте не будем использовать EnvironmentObject, да

2023-04-14 19:30 UTC, StoneSpb approved these changes

2023-04-14 19:30 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject var viewModel: ListScreenViewModel
private?

2023-04-14 19:30 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +    private let navigationTitle = "BeRich"
Можно вынести из класса совсем

2023-04-15 05:42 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject var viewModel: ListScreenViewModel
Точно)
Поправил

2023-04-15 05:42 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +    private let navigationTitle = "BeRich"
Поправил

2023-04-15 11:56 UTC, StoneSpb approved these changes

2023-04-15 11:56 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
> +private enum Const {
ИМХО вы переусложняете )

2023-04-15 18:27 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +private enum Const {
Поправил

2023-04-15 18:36 UTC, DanilaG commented
Не сбрасывались аппрувы при пуше коммитов, поправил

2023-04-16 07:23 UTC, StoneSpb commented on BeRich/Feedback/System.swift
> +        let events = feedbacks.map { feedback in feedback.run(state.eraseToAnyPublisher()) }
```suggestion
        let events = feedbacks.map { $0.run(state.eraseToAnyPublisher()) }
```

2023-04-16 07:25 UTC, StoneSpb commented on BeRich/Feedback/System.swift
> +        .eraseToAnyPublisher()
А точно нужен ещё один erase?

2023-04-16 07:30 UTC, StoneSpb approved these changes

2023-04-16 07:30 UTC, StoneSpb commented on BeRich/ListScreen/ListScreen.swift
>      @StateObject var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
private?

2023-04-16 07:30 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenViewModel.swift
> +        bag.removeAll()
Мне кажется можно не писать, т.к. при deinit bag тоже уничтожится

2023-04-16 15:35 UTC, DanilaG commented on BeRich/ListScreen/ListScreenViewModel.swift
> +        bag.removeAll()
Да, получается, что можно не писать:
https://developer.apple.com/documentation/combine/anycancellable

Поправил

2023-04-16 15:35 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
>      @StateObject var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
Поправил

2023-04-16 15:36 UTC, DanilaG commented on BeRich/Feedback/System.swift
> +        .eraseToAnyPublisher()
Да, иначе ошибка компиляции:
Cannot convert return expression of type 'Deferred<AnyPublisher<State, Publishers.MergeMany<AnyPublisher<Event, Never>>.Failure>>' (aka 'Deferred<AnyPublisher<State, Never>>') to return type 'AnyPublisher<State, Never>'

Но можно убрать первый, и всё ок. Поправил

2023-04-16 15:36 UTC, DanilaG commented on BeRich/Feedback/System.swift
> +        let events = feedbacks.map { feedback in feedback.run(state.eraseToAnyPublisher()) }
Поправил

2023-04-17 06:45 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject private var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
Move to viewModel?

2023-04-17 06:45 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +private let screenTitle = "BeRich"
move to list screen view?

2023-04-17 06:46 UTC, IlyasNN commented on BeRich/ListScreen/ListScreenViewModel.swift
> +    private var bag = Set<AnyCancellable>()
Naming "bag" is not clear

2023-04-17 07:02 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject private var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
Да, по факту она должна быть там. Но tradingDataNetworkFetcher не добавлял в этом ПР, а добавил приват. Думаю что провести этот рефакторинг лучше в отдельной задаче, когда будем подключать сеть.

2023-04-17 07:03 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +private let screenTitle = "BeRich"
Смотри выше) Там было предложение вынести. Предлагаю принять одно общее решение на всех и ему следовать)

2023-04-17 07:06 UTC, DanilaG commented on BeRich/ListScreen/ListScreenViewModel.swift
> +    private var bag = Set<AnyCancellable>()
Да вроде понятно, обычно так и называют) Если bagOfCancellable то длинно звучит. Можно попробовать в subscribers, но не особо разницу вижу. Но если прям нужно и не понятно, то могу переименовать

2023-04-17 07:11 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject private var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
Пока убрал эту строку совсем, так как она не использовалась. Добавлю потом, когда сеть прикручивать в модель будем

2023-04-17 07:12 UTC, DanilaG commented on BeRich/ListScreen/ListScreen.swift
> +private let screenTitle = "BeRich"
https://github.com/BeRich-Team/BeRich/pull/40#discussion_r1167210080

2023-04-17 07:15 UTC, IlyasNN commented on BeRich/ListScreen/ListScreenViewModel.swift
> +    private var bag = Set<AnyCancellable>()
OK

2023-04-17 07:16 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +private let screenTitle = "BeRich"
OK

2023-04-17 07:19 UTC, IlyasNN commented on BeRich/ListScreen/ListScreen.swift
> +    @StateObject private var tradingDataNetworkFetcher = TradingDataNetworkFetcher(request: NetworkService.request)
OK

2023-04-17 07:20 UTC, IlyasNN approved these changes

2023-04-17 10:24 UTC, DanilaG commented
Было цикл по памяти, поправил 
https://developer.apple.com/documentation/combine/just/assign(to:)

2023-04-17 12:15 UTC, StoneSpb approved these changes

2023-04-17 12:24 UTC, andrey-sikerin approved these changes

2023-04-17 12:24 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreen+Factory.swift
> +        let viewModel = ListScreenViewModel()
если что-то (в частности viewModel используется в одном месте) то можно смело в этом место инлайнить

```
static func make() -> some View {
        return ListScreen(viewModel: ListScreenViewModel())
    }
```

2023-04-17 12:24 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreenViewModel.swift
> +        Feedback { _ in input }
Это же заглушка? - давай напишем коммент когда и где она будет реализована?

2023-04-17 13:29 UTC, DanilaG commented on BeRich/ListScreen/ListScreenViewModel.swift
> +        Feedback { _ in input }
Поправил

2023-04-17 13:30 UTC, merged