python and swift recognition of 5 patterns
BeRich-Team/BeRich pull request #41
Opened 2023-04-14 14:49 UTC by valeriiAndreev

5 patterns on python and sme functions on swift

2023-04-14 19:23 UTC, StoneSpb requested changes

2023-04-14 19:23 UTC, StoneSpb commented on BeRich/PatternRecognition/CandlePatternRecognitionFunctions.swift
> +
Давай обернём это всё в `enum CanclePatternRecognitionFunctions {`: https://forums.swift.org/t/an-enum-based-approach-to-namespaces/12487

Тогда это не будут свободные функции, т.к. они не тянут на функции общего назначения типа max, min и т.п.

2023-04-14 19:23 UTC, StoneSpb commented on BeRich/PatternRecognition/CandlePatternRecognitionFunctions.swift
По данному файлу нужно пройтись с помощью swiftformat (у нас по этой причине в этом реквесте не прошли проверки на CI).
В идеале - поставить себе на машину, например с помощью homebrew: https://docs.brew.sh/Homebrew-on-Linux
Либо другим способом.
Либо на худой конец попросить коллег пройтись форматтером :)

2023-04-14 19:23 UTC, StoneSpb commented on BeRich/PatternRecognition/CandlePatternRecognitionFunctions.swift
> +print(ext_near(x:1000.0,y:1005.0))
Наверное лучше эти print'ы закомментировать во вливаемом коде

2023-04-15 11:42 UTC, StoneSpb approved these changes

2023-04-15 11:43 UTC, andrey-sikerin approved these changes

2023-04-15 11:43 UTC, merged