Feature/chart view
BeRich-Team/BeRich pull request #44
Opened 2023-04-14 16:10 UTC by Maksim193

#11

2023-04-14 20:09 UTC, StoneSpb requested changes

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                                                            let element = findElement(location: value.location, proxy: proxy, geometry: nthGeometryItem, data: data)
Здесь нужно хорошенько поработать над декомпозицией:
- с таким диким сдвигом (indentation) читать код невероятно сложно
- сложность кода в данной вьюхе тоже зашкаливает. Здесь мы перемешали и визуальное отображение, и реакцию на жесты, другие события. Всё это нужно разнести как минимум на методы

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                                                                .onChanged { value in
Можно не писать `value in`, если код в кложуре не сильно потеряет в читаемости (субъективный параметр). Мне в целом `$0.location` будет привычно, но тут смотри сам.

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                                                            let element = findElement(location: value.location, proxy: proxy, geometry: nthGeometryItem, data: data)
Кажется это копипаста

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                //                .padding([.leading], -150)
Всё ещё нужно?

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                // MARK: - НЕ ТРОГАТЬ СТРОКУ НИЖЕ! ОНА КАСТЫЛИТ ОТОБРАЖЕНИЕ ОСИ Y
От слова "каст" видимо ;)

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                    RectangleMark( // Прямоугольничек (где открылся и где закрылся)
Здесь можно воспользоваться терминологией - это называется "телом" свечи: https://traderblog.net/japonskie-svechi/

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                        yEnd: .value("Close", Stock.exampleData[0].closePrice),
А почему всегда 0?

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/CandlesView.swift
> +                // Полосочка (миниум и максимум за день)
```suggestion
                // Полосочка (минимум и максимум за день)
```

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/CandlesView.swift
> +                // Полосочка (миниум и максимум за день)
"Полосочка" - это "тень" свечи: https://traderblog.net/japonskie-svechi/

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                        yEnd: .value("Close", Stock.exampleData[0].closePrice),
Возможно этот код больше не нужен, тогда следует прибраться

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/CandlesView.swift
> +                // Прямоугольничек (где открылся и где закрылся)
Здесь можно воспользоваться терминологией - это называется "телом" свечи: https://traderblog.net/japonskie-svechi/

2023-04-14 20:09 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/ChartUnderlayForScroll.swift
> +            // Пока у них id это их порядковый номер, потом можем как нибудь
```suggestion
            // Пока у них id это их порядковый номер, потом можем как-нибудь
```

2023-04-15 14:28 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/CandlesView.swift
> +                // Полосочка (миниум и максимум за день)
FIXED

2023-04-15 14:28 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/CandlesView.swift
> +                // Прямоугольничек (где открылся и где закрылся)
FIXED

2023-04-15 14:29 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/ChartUnderlayForScroll.swift
> +            // Пока у них id это их порядковый номер, потом можем как нибудь
FIXED

2023-04-15 14:30 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/ChartView.swift
> +                        if let selectedElement = selectedElement {
FIXED

2023-04-15 14:33 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/ChartView.swift
> +                            VStack(alignment: .leading) {
FIXED

2023-04-15 14:33 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +    // Далее это будет либо id паттерна, либо закастылено id свечи в нужном паттерне
FIXED

2023-04-15 14:35 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                                                                .onChanged { value in
FIXED

2023-04-15 14:36 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +                    RectangleMark( // Прямоугольничек (где открылся и где закрылся)
FIXED

2023-04-15 14:36 UTC, IlyasNN commented on BeRich/DetailedTickerScreen/DetailedTickerScreen.swift
> +    @State var isFavourite = false
FIXED

2023-04-15 18:15 UTC, StoneSpb requested changes

2023-04-15 18:15 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/ChartTimePeriod.swift
> +    var id: String {
Не очень хорошо получилось. Каждый раз когда ты обратишься к `id` - получишь новое значение. А мы не можем просто использовать `rawValue` в качестве идентификатора? В рамках enum'а значение уникально

2023-04-15 18:15 UTC, StoneSpb commented on BeRich/DetailedTickerScreen/ChartView/InternalChartView.swift
> +    var body: some View {
Вот этот кусок кода всё ещё хочется декомпозировать.

2023-04-15 18:15 UTC, StoneSpb commented on BeRich/ListScreen/Stock.swift
> +    let dateFormatter: DateFormatter = {
Не нужно создавать по форматтеру на каждую свечу, давайте один статический ниже заведём

2023-04-17 11:09 UTC, andrey-sikerin submitted a review, later dismissed

2023-04-17 11:31 UTC, andrey-sikerin approved these changes

2023-04-17 11:32 UTC, StoneSpb approved these changes

2023-04-17 11:32 UTC, merged