[#68] Connect load
BeRich-Team/BeRich pull request #69
Opened 2023-04-17 21:30 UTC by DanilaG

Добавдена загрузка тикеров

2023-04-18 07:10 UTC, andrey-sikerin requested changes

2023-04-18 07:10 UTC, andrey-sikerin commented on BeRich/Fakes.swift
> +        func set(isFavourite _: Bool, for _: Ticker) {}
эта функция используется?

2023-04-18 07:10 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreen+Factory.swift
>      }
если созданный объект используется в одном месте то обычно он инланится в точку использования




````
static func make() -> some View {
        return ListScreen(
            viewModel: ListScreenViewModel(
                useCase: ListScreenUseCaseImpl(
                    tradingDataNetworkFetching: TradingDataNetworkFetcher()
                )
            )
        )
    }
```

2023-04-18 07:10 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreenUseCase.swift
> +protocol ListScreenUseCase {
протокол с одним методом можно выразить как typealiase в свифте. Здесь в этом протоколе еще будут методы?

2023-04-18 07:10 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreenUseCase.swift
> +struct ListScreenLoadingError: Error {}
enum ClientSpecificError: Error {
    case clientError
    case baseError(BaseError)
}

ошибки вот так обычно выражают - зачем тебе структура?

2023-04-18 07:10 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreenUseCase.swift
> +struct ListScreenLoadingError: Error {}
предложу (если вообще такая ошибка нужна переместить ее объявление вниз файла

2023-04-18 08:25 UTC, StoneSpb requested changes

2023-04-18 08:25 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenUseCase.swift
> +    let tradingDataNetworkFetching: TradingDataNetworkFetching
```suggestion
    let fetcher: TradingDataNetworkFetching
```

2023-04-18 08:25 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenViewModel.swift
> +                    let tickers: [Ticker] = await (try? useCase.getTickers()) ?? []
А почему мы не фейлим промис, если не смогли загрузить тикеры?

2023-04-18 08:28 UTC, DanilaG commented on BeRich/Fakes.swift
> +        func set(isFavourite _: Bool, for _: Ticker) {}
Убрал

2023-04-18 08:28 UTC, DanilaG commented on BeRich/ListScreen/ListScreen+Factory.swift
>      }
Поправил

2023-04-18 08:28 UTC, DanilaG commented on BeRich/ListScreen/ListScreenUseCase.swift
> +struct ListScreenLoadingError: Error {}
Так как enum содердит только 1 ошибку, то решил сделать по аналогии с свифтовой CancellationError. Но разницы нет, поправил

2023-04-18 08:29 UTC, DanilaG commented on BeRich/ListScreen/ListScreenUseCase.swift
> +struct ListScreenLoadingError: Error {}
Выенес в отдельный файл все ошибки экрана

2023-04-18 09:37 UTC, DanilaG commented on BeRich/ListScreen/ListScreenUseCase.swift
> +    let tradingDataNetworkFetching: TradingDataNetworkFetching
Поправил

2023-04-18 09:38 UTC, DanilaG commented on BeRich/ListScreen/ListScreenViewModel.swift
> +                    let tickers: [Ticker] = await (try? useCase.getTickers()) ?? []
Тут потерял обработчик ошибки, поправил, проверил)
Но всё равно, отдаёт success, так как задача методов Future генерировать события. И если была ошибка загрузки, то генерируется событие ошибки

2023-04-18 14:26 UTC, andrey-sikerin approved these changes

2023-04-18 14:26 UTC, andrey-sikerin commented on BeRich/ListScreen/ListScreenErrors.swift
> +//
предложу убирать эти комменты в начале файла

2023-04-18 20:10 UTC, StoneSpb approved these changes

2023-04-18 20:10 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenErrors.swift
> +//
Может swiftformat умеет это делать?

2023-04-18 20:10 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenErrors.swift
> +    case loading
Непонятно что означает данная ошибка

2023-04-18 20:10 UTC, StoneSpb commented on BeRich/ListScreen/ListScreenUseCase.swift
> +    func getTickers() async throws -> [Ticker]
Вместо
```
protocol ListScreenUseCase {
    func getTickers() async throws -> [Ticker]
}
```
Нужно сделать
```
typealias GetTickersListScreenUseCase = () async throws -> [Ticker]
```

2023-04-19 08:52 UTC, closed without merging

2023-04-19 08:53 UTC, DanilaG commented
Решили не делать пока бинанс, а использовать moex