[79] Pattern detector
BeRich-Team/BeRich pull request #81
Opened 2023-04-18 20:54 UTC by IlyasNN

Добавлен паттерн детектор, который принимает на вход массив свечей и выдает массив всех распознанных паттернов. 

Распознанный патерн имеет в себе:
1) Начало (Date)
2) Конец (Date)
3) Название паттерна на русском языке
4) Максимальная цена среди значимых свеч в паттерне
5) Минимальная цена среди значимых свеч в паттерне

2023-04-18 21:05 UTC, StoneSpb requested changes

2023-04-18 21:05 UTC, StoneSpb commented on BeRichTests/PatternRecognitionTests.swift
> +        let bundle = Bundle(for: type(of: self))
Почему решил снести `Bundle.module`? Без него не работало на linux

2023-04-18 21:05 UTC, StoneSpb commented on BeRichTests/PatternRecognitionTests.swift
> +        let detectedPatterns = patternDetector.detectPattern(candelsticks: candlesticks,
Предложу ещё проверять параметры найденных паттернов (интервалы в массиве данных)

2023-04-18 21:05 UTC, StoneSpb commented on BeRich/PatternDetector/PatternDetector.swift
> +    func detectPatterns(candles: [Stock]) -> [DetectedPattern] {
Добавим тест и на такой метод?

2023-04-18 21:07 UTC, IlyasNN commented on BeRichTests/PatternRecognitionTests.swift
> +        let bundle = Bundle(for: type(of: self))
А с ним не работает в Xcode)

2023-04-18 21:09 UTC, IlyasNN commented on BeRichTests/PatternRecognitionTests.swift
> +        let detectedPatterns = patternDetector.detectPattern(candelsticks: candlesticks,
Хорошее замечание, но написать качественные тесты займет достаточное количество времени. Сейчас нужно заметить текущий форматер. Создам тикет на доп тесты, если успеем, затестим!

2023-04-18 21:10 UTC, IlyasNN commented on BeRichTests/PatternRecognitionTests.swift
> +        let detectedPatterns = patternDetector.detectPattern(candelsticks: candlesticks,
#82

2023-04-18 21:11 UTC, IlyasNN commented on BeRich/PatternDetector/PatternDetector.swift
> +    func detectPatterns(candles: [Stock]) -> [DetectedPattern] {
Да, хотел, но не смогу быстро сгенерировать много [Stock] из csv...
Думаю также в рамках #82 сделать. Сейчас PatternDetector нужен быстрее в мейн для второго экрана

2023-04-19 06:00 UTC, StoneSpb approved these changes

2023-04-19 06:00 UTC, StoneSpb commented on BeRichTests/PatternRecognitionTests.swift
> +        let bundle = Bundle(for: type(of: self))
Упс. А какая возникает ошибка?

2023-04-19 06:01 UTC, StoneSpb commented on BeRichTests/PatternRecognitionTests.swift
> +        let bundle = Bundle(for: type(of: self))
Здесь можно тестить, делая `swift test` из директории проекта. Если собралось и тесты успешно прогнались - то и на linux должны пройти.

2023-04-19 08:28 UTC, andrey-sikerin approved these changes

2023-04-19 08:34 UTC, merged